### ISSUE TITLE
🐞 PEP621ValidationError

### ISSUE THREAD

**Issue by Redlnn** [GreyElaina/Mina#4]
`pdm.pep517.exceptions.PEP621ValidationError` error when run `pdm build` and `pdm mina build test`

### log:

```text
pdm.pep517.exceptions.PEP621ValidationError: {'includes': ['unknown field'], 'name': ['required field'], 'override': ['unknown field'], 'project': ['unknown field']}
```

### `pyproject.toml`:

```toml
[project]
name = "graiax"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    {name = "GraiaCommunity"},
]
dependencies = [
    "pdm-mina>=0.1.0",
    "mina-build>=0.2.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]

[project.entry-points.pdm]
mina = "mina.plugin:ensure_pdm"

[build-system]
requires = ["mina-build>=0.2.0"]
build-backend = "mina.build"

[tool.mina]
enabled = true

[tool.mina.packages."test"]
override = false
includes = [
    "packages/test"
]

[tool.mina.packages."test".project]
name = "test"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    {name = "Redlnn", email = "w731347477@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
license = {text = "MIT"}
```
